name: Ola mundo
on: push
jobs:
  minha-tarefa:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: echo "Vitor Hugo Gilhi da Silva"
      - name: Dizer ola
        run: echo "Commit feito por ${{github.actor}}"
